name: Use Secret in JS Code

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  accessSecret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use Secret in JS Code
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # Set the secret as an environment variable
        run: |
          echo "Should be able to access secret in JavaScript code..."
          node temp.js
